Website-Sell-Cosmetics-main/CosmeticsStore/Controllers/AuthenSitesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CosmeticsStore.Models;

namespace CosmeticsStore.Controllers
{
    public class AuthenSitesController : Controller
    {
        CosmeticsStoreDbContext db = new CosmeticsStoreDbContext();

        // GET: Authen
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Dotask()
        {
            string account = Request["account"];
            string password = Request["password"];
            var f_password = Commons.GetMD5(password);
            var data = db.Customers.Where(s => s.UserName.Equals(account) && s.Password.Equals(f_password) && s.Status != false).ToList();

            if (data.Count() > 0)
            {
                Session["user"] = data.FirstOrDefault();
                if (Session["GioHang"] == null)
                {
                    return RedirectToAction("Index", "Home");
                }
                return RedirectToAction("XemGioHang", "Cart");
            }
            else
            {
                ModelState.AddModelError("ErrorLogin", "Tài khoản hoặc mật khẩu không chính sác!");
                return View("Login");

            }

        }
        public ActionResult Logout()
        {
            Session["user"] = null;
            return RedirectToAction("Index", "Home");
        }
        // GET: Admin/Customers/Create
      
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(Customer customer)
        {
            if (ModelState.IsValid)
            {
                var MaHMD5 = Commons.GetMD5(customer.Password);
                customer.Password = MaHMD5;
                if (db.Customers.Any(x => x.UserName == customer.UserName))
                {
                    ModelState.AddModelError("ErrorUserName", "Tài khoản đã tồn tại!");
                }
                else if (db.Customers.Any(x => x.Email == customer.Email))
                {
                    ModelState.AddModelError("ErrorEmail", "Email đã tồn tại!");
                }
                else
                {
                    customer.Status = true;
                    customer.Role = "Khách Hàng";
                    db.Customers.Add(customer);
                    db.SaveChanges();
                    return RedirectToAction("Login");
                }
            }
            return View(customer);
        }
        public ActionResult EditAccount(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditAccount([Bind(Include = "CustomerID,UserName,Password,Name,Image,Address,Email,Phone,AgentID,Status,Question,Answer")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                var MaHMD5 = Commons.GetMD5(customer.Password);
                customer.Password = MaHMD5;
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                Session["user"] = null;
                return RedirectToAction("Index","Home");
            }
            return View(customer);
        }
    }
}

Website-Sell-Cosmetics-main/CosmeticsStore/Views/AuthenSites/EditAccount.cshtml
@{ var user = Session["user"] as CosmeticsStore.Models.Customer; }
@model CosmeticsStore.Models.Customer

@{
    ViewBag.Title = "Thay đổi thông tin";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
@section jsSite{
    <script>
        $('#btnSelectImage').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#Image').val(url);
            };
            finder.popup();
        })
    </script>
}
<style>
    .main {
        margin-bottom: 30px;
    }

    .heading {
        color: var(--default-cl);
        font-size: 2rem;
        text-transform: uppercase;
        border-bottom: 2px solid rgba(0,0,0,0.2);
        padding: 20px 0 12px 0;
    }

    .form-horizontal {
        display: flex;
        flex-wrap: wrap;
        margin-left: -20px;
        margin-right: -20px;
    }

    .form-label {
        font-size: 1.6rem;
        margin-bottom: 10px;
        display:block;
    }

    .form-group {
        margin-top: 20px;
        flex: 0 0 50%;
        max-width: 50%;
        padding-left: 20px;
        padding-right: 20px;
    }

    .form-group2 {
        text-align: center;
        width: 100%;
    }

    .text-danger {
        display: block;
        color: red;
        height: 20px;
        padding-top: 6px;
        font-size: 1.4rem;
    }

    .form-control {
        margin-top: 0;
    }

    .wrapSelectImage {
        position: relative;
    }

    #btnSelectImage {
        position: absolute;
        right: 0;
        height: 100%;
        border: none;
        outline: none;
        width: 40px;
        font-size: 1.6rem;
    }
</style>
@if (user != null)
{
    <div class="main">
        <div class="grid wide">
            <h3 class="heading">Thay đổi thông tin tài khoản</h3>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.CustomerID)
                    @Html.HiddenFor(model => model.UserName)
                    <div class="form-group ">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "form-label" })
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group ">
                        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "form-label" })
                        @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group ">
                        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "form-label" })
                        <div class="wrapSelectImage">
                            @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                            <button id="btnSelectImage">...</button>
                        </div>
                        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group ">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "form-label" })
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group ">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "form-label" })
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group ">
                        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "form-label" })
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group2">
                        <input type="submit" value="Cập Nhật" class="btn btn--default" />
                    </div>
                </div>
            }
        </div>
    </div>
}
else
{
    <div class="main">
        <div class="grid wide">
            <h3 class="heading">Bạn cần đăng nhập tài khoản trước</h3>
        </div>
    </div>
}

@Scripts.Render("~/JsAdminCK_")

Website-Sell-Cosmetics-main/CosmeticsStore/Views/AuthenSites/Login.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Đăng nhập</title>
    <link href="~/Content/AuthenForms/style.css" rel="stylesheet" />
</head>

<body>
    <div class="main">
        <form action="/AuthenSites/Dotask" method="POST" class="form" id="form-1">
            <h3 class="heading">Đăng nhập</h3>
            <p class="desc">Cùng nhau mua đất tại Quang chè ❤️</p>
            <div class="spacer"></div>
            <div class="wrapitem-center">
            </div>
            <div class="form-group">
                <label for="fullname" class="form-label">Tài khoản</label>
                <input id="account" name="account" type="text" placeholder="VD: Sơn Đặng" class="form-control">
                <span class="form-message"></span>
            </div>
            <div class="form-group">
                <label for="password" class="form-label">Mật khẩu</label>
                <input id="password" name="password" type="password" placeholder="Nhập mật khẩu" class="form-control">
                <span class="form-message"></span>
            </div>
            @Html.ValidationMessage("ErrorLogin", new { @class = "form-info" })
            <button class="form-submit">Đăng Nhập</button>
            <div class="wrapitem-center">
                <a class="form-link" href="@Url.Action("Register","AuthenSites")">Chưa có tài khoản? <b>Đăng Kí</b></a>
            </div>
        </form>

    </div>
    <script src="~/Content/AuthenForms/validator.js"></script>
    <script>
        Validator({
            form: 'form-1',
            errorSelector: '.form-message',
            formGroup: '.form-group',
            rules: [
                Validator.isRequired('#account'),
                Validator.minLength('#password', 6),
            ]
        })
    </script>
</body>

</html>

Website-Sell-Cosmetics-main/CosmeticsStore/Views/AuthenSites/Register.cshtml
@model CosmeticsStore.Models.Customer

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Đăng kí</title>
    <link href="~/Content/AuthenForms/style.css" rel="stylesheet" />
    <link href="~/Content/AuthenForms/style2.css" rel="stylesheet" />
</head>

<body>
    <div class="main">
        <form action="/AuthenSites/Register" method="POST" class="form" id="form-1">
            @Html.AntiForgeryToken()
            <h3 class="heading">Thành viên đăng ký</h3>
			<p class="desc">Cùng nhau mua chè tại Quang Chè ❤️</p>
            <div class="spacer"></div>
            <div class="wrapitem-center">
                @Html.ValidationMessage("ErrorUserName", new { @class = "form-info" })
                @Html.ValidationMessage("ErrorEmail", new { @class = "form-info" })
            </div>
            <div class="form-group">
                <label for="fullname" class="form-label">Họ Tên</label>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "VD: Quang" } })
                <span class="form-message"></span>
            </div>
            <div class="form-group">
                <label for="account" class="form-label">Tài khoản</label>
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @placeholder = "VD:Quang203" } })
                <span class="form-message"></span>
            </div>
            <div class="form-group">
                <label for="password" class="form-label">Mật khẩu</label>
                @Html.PasswordFor(model => model.Password, new { @class = "form-control", @placeholder = "Nhập mật khẩu" })
                <span class="form-message"></span>
            </div>
            <div class="form-group">
                <label for="password_confirmation" class="form-label">Nhập lại mật khẩu</label>
                <input id="password_confirmation" name="password_confirmation" placeholder="Nhập lại mật khẩu" type="password" class="form-control">
                <span class="form-message"></span>
            </div>
            <div class="form-group">
                <label for="email" class="form-label">Email</label>
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "VD: quang203@gmail.com" } })
                <span class="form-message"></span>
            </div>
            <div class="form-group">
                <label for="address" class="form-label">Địa chỉ</label>
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @placeholder = "VD: 234 Lê Quý Đôn, Tp.Thái Bình" } })
                <span class="form-message"></span>
            </div>
            <div class="form-group">
                <label for="address" class="form-label">Số điện thoại</label>
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", @placeholder = "VD: 0346587763" } })
                <span class="form-message"></span>
            </div>
            <div class="wrapitem-center">
                <button class="form-submit">Đăng ký</button>
            </div>
            <div class="wrapitem-center">
                <a class="form-link" href="@Url.Action("Login","AuthenSites")">Đã có tài khoản? <b>Đăng Nhập</b></a>
            </div>
        </form>
    </div>
    <script src="~/Content/AuthenForms/validator.js"></script>

    <script>
        Validator({
            form: 'form-1',
            errorSelector: '.form-message',
            formGroup: '.form-group',
            rules: [
                Validator.isRequired('#Name'),
                Validator.isRequired('#UserName'),
                Validator.minLength('#Password', 6),
                Validator.isRequired('#password_confirmation'),
                Validator.isConfirm('#password_confirmation', function () {
                    return document.querySelector('#form-1 #Password').value
                }, 'Mật khẩu nhập lại không chính xác'),
                Validator.isEmail('#Email'),
                Validator.isRequired('#Address'),
                Validator.isRequired('#Phone'),
            ]
        })
    </script>
</body>

</html>